### ISSUE TITLE
SLF4J compatibility

### ISSUE THREAD

**Issue by mcandre** [scireum/sirius-kernel#41]
Please help us use sirius-kernel in larger projects that require SLF4J. Please do at least one of:
- Don't rely on logging method calls specific to log4j, that are not available in projects that prefer SLF4J.
- Have sirius-kernel use SLF4J itself, to ensure SLF4J compatibility
- Show a Maven or Gradle snippet that will work for other projects attempting to include sirius-kernel, in a way that resolves the SLF4J incompatibility

**Comment by andyHa** [comment]
I understand that this issue is outdated - still for future reference:
You need to provide a custom "Setup" class which doesn't setup log4j as default logger for everything.

Using maven you also could then exclude the dependency to log4j. The whole project only relies on our logging interface.
